title: Artgrupa Agencja Artystyczna
name: Oficjalna strona
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://localhost:4000" # development
# url: "https://artgrupa.net" # production
url: "https://dwoznicka.github.io/artgrupa" # github pages

copyright: 2024 © <a href="https://artgrupa.net" class="site-link">ARTGRUPA</a>. Wszelkie prawa zastrzeżone.
copyright_short: 2024 © <a href="https://artgrupa.net" class="site-link">ARTGRUPA</a>.
made_by: 'Made with ❤ by <a href="https://www.facebook.com/Daria.Woznicka/" target="_blank">DW</a>'
# Build settings
markdown: kramdown
incremental: true
plugins:
  - jekyll-assets
exclude:
- CNAME
- .gitignore
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- .ruby-version
- Guardfile
- .jekyll-assets-cache
- .sass-cache
- .editorconfig
- .idea
- .ruby-version
- .asset-cache
- _docs

